"""add creator foreign key

Revision ID: 387e381fb912
Revises: d617e03f4939
Create Date: 2026-09-19 19:31:40.427288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387e381fb912'
down_revision: Union[str, Sequence[str], None] = 'd617e03f4939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'greenhouse_gases', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'greenhouse_gases', type_='foreignkey')
    # ### end Alembic commands ###
